#!/usr/bin/env python3
# inject_vba_ppk.py — Jalankan SEKALI untuk inject/update modul VBA ke xlsm
# Menggunakan Excel COM (DispatchEx) — Excel harus DITUTUP sebelum menjalankan ini
import sys, os
from datetime import datetime


def _configured_path(name):
    value = os.environ.get(name, '').strip().strip('"')
    return os.path.normpath(value) if value else ''


# Injector berjalan dari clone/runtime lokal; workbook target tetap boleh berada di Drive.
_python_exe = _configured_path('POKJA_PYTHON')
_site_packages = os.path.join(os.path.dirname(_python_exe), 'Lib', 'site-packages') if _python_exe else ''
if _site_packages and os.path.isdir(_site_packages):
    sys.path.insert(0, _site_packages)

INJECTOR_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.normpath(os.path.join(INJECTOR_DIR, '..'))
if len(sys.argv) > 1:
    EXCEL_PATH = os.path.abspath(sys.argv[1])
else:
    configured_workbook = _configured_path('PPK_MASTER_WORKBOOK')
    if not configured_workbook:
        raise SystemExit(
            'ERROR: Beri path workbook .xlsm sebagai argumen pertama '
            'atau set PPK_MASTER_WORKBOOK.'
        )
    EXCEL_PATH = configured_workbook
PACKAGE_DIR = os.path.dirname(EXCEL_PATH)
BAT_PATH   = os.path.join(PACKAGE_DIR, '__ppk_runtime', 'generate_dokumen_ppk.bat')

VBA_CODE = r'''
' ModGeneratePPK — Auto-generated by inject_vba_ppk.py
' Berisi 9 Sub: GenerateDokumen, PrintPDF, PrintAllPDF, PrintPilihanPDF, GenerateSemua, CommitPaket, NomorBaru, MuatDariDB, GeneratePilihan

' ─── Helper portabel: runtime terpisah dari workbook ─────────────────────────
Private Function GetRuntimePath() As String
    GetRuntimePath = ThisWorkbook.Path & "\__ppk_runtime"
End Function

Private Function GetBatPath() As String
    GetBatPath = GetRuntimePath() & "\generate_dokumen_ppk.bat"
End Function

Private Function GetLogPath() As String
    GetLogPath = GetRuntimePath() & "\generate_log.txt"
End Function

' ─── Helper: jalankan bat dengan argumen, return exit code ─────────────────
Private Function JalankanBat(args As String) As Long
    Dim wsh As Object
    Set wsh = CreateObject("WScript.Shell")
    JalankanBat = wsh.Run("""" & GetBatPath() & """ " & args, 0, True)
    Set wsh = Nothing
End Function

' ─── Helper: baca log file, filter baris teknis/noise ─────────────────────
Private Function BacaLog() As String
    Dim fso As Object, ts As Object
    Set fso = CreateObject("Scripting.FileSystemObject")
    If Not fso.FileExists(GetLogPath()) Then
        BacaLog = "(log tidak ditemukan)"
        Exit Function
    End If
    Set ts = fso.OpenTextFile(GetLogPath(), 1)
    Dim raw As String
    raw = ts.ReadAll
    ts.Close
    BacaLog = raw
End Function

' ─── Helper: filter log hanya baris penting untuk notifikasi ───────────────
Private Function RingkasLog(raw As String) As String
    Dim lines() As String
    lines = Split(raw, Chr(10))
    Dim out As String
    Dim i As Long
    Dim skipPthNoise As Boolean
    For i = 0 To UBound(lines)
        Dim ln As String
        ln = Trim(lines(i))
        If ln = "" Then GoTo Skip
        If skipPthNoise Then
            If InStr(ln, "Remainder of file ignored") > 0 Then skipPthNoise = False
            GoTo Skip
        End If
        If InStr(ln, "Error processing line") > 0 Or _
           InStr(ln, "sphinxcontrib_jsmath") > 0 Then
            skipPthNoise = True
            GoTo Skip
        End If
        ' Skip baris noise teknis
        If InStr(ln, "SyntaxWarning") > 0 Then GoTo Skip
        If InStr(ln, "generate_dokumen_ppk.py:") > 0 Then GoTo Skip
        If Left(ln, 3) = Chr(34) & Chr(34) & Chr(34) Then GoTo Skip
        If InStr(ln, "Auto-terbilang:") > 0 Then GoTo Skip
        If InStr(ln, "Auto-detect:") > 0 Then GoTo Skip
        If InStr(ln, "=== Mode:") > 0 Then GoTo Skip
        If Left(ln, 7) = "Folder:" Then GoTo Skip
        If Left(ln, 7) = "Output " Then GoTo Skip
        out = out & ln & Chr(10)
        Skip:
    Next i
    RingkasLog = Trim(out)
End Function

' ─── 1. Generate Dokumen ────────────────────────────────────────────────────
Sub GenerateDokumen()
    If MsgBox("Generate semua dokumen dari Master Data?" & Chr(13) & _
              "Dokumen lama di folder output akan ditimpa.", _
              vbQuestion + vbYesNo, "Konfirmasi Generate") = vbNo Then Exit Sub

    ThisWorkbook.Save

    Dim ret As Long
    ret = JalankanBat("--mode generate")

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        MsgBox "✅ Dokumen berhasil di-generate!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbInformation, "Generate Selesai"
    Else
        MsgBox "❌ Generate gagal." & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbCritical, "Generate Gagal"
    End If

    Application.ScreenUpdating = True
    ThisWorkbook.Sheets("Master Data").Activate
End Sub

' ─── 2. Print PDF (generate langsung ke PDF, tanpa .docx di folder output) ──
Sub PrintPDF()
    If MsgBox("Generate dokumen langsung sebagai PDF?" & Chr(13) & _
              "Folder output akan berisi file PDF saja (tanpa .docx).", _
              vbQuestion + vbYesNo, "Konfirmasi Generate PDF") = vbNo Then Exit Sub

    ThisWorkbook.Save

    Dim ret As Long
    ret = JalankanBat("--mode pdf-only")

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        MsgBox "✅ PDF berhasil di-generate!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbInformation, "Generate PDF Selesai"
    Else
        MsgBox "⚠️ Generate PDF selesai (ada error)." & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbExclamation, "Generate PDF"
    End If
End Sub

' ─── 3. Print All PDF (semua subfolder di folder ini) ──────────────────────
Sub PrintAllPDF()
    If MsgBox("Convert semua dokumen Word di SEMUA folder paket menjadi PDF?" & Chr(13) & _
              "Proses ini mungkin memakan waktu beberapa menit.", _
              vbQuestion + vbYesNo, "Konfirmasi Print All PDF") = vbNo Then Exit Sub

    Dim ret As Long
    ret = JalankanBat("--mode print-all")

    Dim msg As String
    msg = BacaLog()
    If ret = 0 Then
        MsgBox "✅ Print All PDF selesai." & Chr(13) & Chr(13) & _
               Left(RingkasLog(msg), 600), vbInformation, "Print All PDF"
    Else
        MsgBox "⚠️ Print All PDF selesai (ada error)." & Chr(13) & Chr(13) & _
               Left(RingkasLog(msg), 600), vbExclamation, "Print All PDF"
    End If
End Sub

' ─── 4. Print Pilihan PDF (folder/paket tertentu saja) ─────────────────────
Sub PrintPilihanPDF()
    Dim nomor As String
    nomor = InputBox("Masukkan nomor paket yang ingin di-print PDF:" & Chr(13) & _
                     "Pisah dengan koma untuk beberapa paket." & Chr(13) & _
                     "Contoh: 1,3,5  atau  2", "Print Pilihan PDF")
    If Trim(nomor) = "" Then Exit Sub
    Dim ret As Long
    ret = JalankanBat("--mode print-pilihan --nomor " & nomor)
    Dim msg As String
    msg = BacaLog()
    If ret = 0 Then
        MsgBox "✅ Print Pilihan PDF selesai." & Chr(13) & Chr(13) & _
               Left(RingkasLog(msg), 600), vbInformation, "Print Pilihan PDF"
    Else
        MsgBox "⚠️ Print Pilihan PDF selesai (ada error)." & Chr(13) & Chr(13) & _
               Left(RingkasLog(msg), 600), vbExclamation, "Print Pilihan PDF"
    End If
End Sub

' ─── 5. Generate Semua (multi-paket dari sheet Daftar Paket) ────────────────
Sub GenerateSemua()
    If MsgBox("Generate dokumen untuk SEMUA paket di sheet 'Daftar Paket'?" & Chr(13) & _
              "Paket dengan status 'SUKSES' akan di-skip.", _
              vbQuestion + vbYesNo, "Konfirmasi Generate Semua") = vbNo Then Exit Sub

    ThisWorkbook.Save

    Dim ret As Long
    ret = JalankanBat("--mode multi")

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        MsgBox "✅ Generate semua paket selesai!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbInformation, "Generate Semua Selesai"
    Else
        MsgBox "❌ Generate semua gagal." & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 600), vbCritical, "Error"
    End If

    Application.ScreenUpdating = True
    If SheetExists("Daftar Paket") Then
        ThisWorkbook.Sheets("Daftar Paket").Activate
    End If
End Sub

' ─── 5. Commit Paket (salin Master Data ke Daftar Paket) ────────────────────
Sub CommitPaket()
    If MsgBox("Salin data Master Data saat ini ke sheet 'Daftar Paket'?" & Chr(13) & _
              "Gunakan ini setelah mengisi data paket lengkap," & Chr(13) & _
              "sebelum reset untuk paket berikutnya.", _
              vbQuestion + vbYesNo, "Konfirmasi Commit Paket") = vbNo Then Exit Sub

    If Not SheetExists("Daftar Paket") Then
        MsgBox "Sheet 'Daftar Paket' tidak ditemukan. Jalankan inject_vba_ppk.py dulu.", vbCritical
        Exit Sub
    End If

    Dim wsMD As Worksheet, wsDP As Worksheet
    Set wsMD = ThisWorkbook.Sheets("Master Data")
    Set wsDP = ThisWorkbook.Sheets("Daftar Paket")

    ' Baca field dari Master Data (kolom A = label, kolom B = nilai)
    Dim fields As Object
    Set fields = CreateObject("Scripting.Dictionary")
    Dim r As Long
    For r = 3 To wsMD.UsedRange.Rows.Count + 2
        Dim lbl As String, val As String
        lbl = Trim(CStr(wsMD.Cells(r, 1).Value & ""))
        val = Trim(CStr(wsMD.Cells(r, 2).Value & ""))
        If lbl <> "" Then fields(lbl) = val
    Next r

    ' Cari apakah Kode RUP sudah ada di Daftar Paket (mode update vs insert)
    Dim kodeRupBaru As String
    kodeRupBaru = Trim(fields("Kode RUP"))
    Dim existingRow As Long
    existingRow = 0
    Dim lastRow As Long
    lastRow = wsDP.Cells(wsDP.Rows.Count, 2).End(xlUp).Row
    If lastRow < 1 Then lastRow = 1
    Dim rx As Long
    For rx = 2 To lastRow
        Dim existKode As String
        existKode = Trim(CStr(wsDP.Cells(rx, 4).Value & ""))
        ' strip .0 suffix (Excel COM kadang return float)
        If Right(existKode, 2) = ".0" Then existKode = Left(existKode, Len(existKode) - 2)
        If existKode = kodeRupBaru Then
            existingRow = rx
            Exit For
        End If
    Next rx

    Dim nextRow As Long
    Dim noUrut As Long
    Dim isUpdate As Boolean
    isUpdate = (existingRow > 0)

    If isUpdate Then
        ' Update baris existing — pertahankan nomor urut lama
        nextRow = existingRow
        noUrut = CLng(wsDP.Cells(nextRow, 1).Value)
    Else
        ' Insert baris baru
        nextRow = lastRow + 1
        If nextRow < 2 Then nextRow = 2
        noUrut = nextRow - 1
    End If

    ' Tulis data ke Daftar Paket
    wsDP.Cells(nextRow, 1).Value = noUrut
    wsDP.Cells(nextRow, 2).Value = fields("Nama Paket (Lengkap)")
    wsDP.Cells(nextRow, 3).Value = fields("Nama Paket (Lengkap)")
    wsDP.Cells(nextRow, 4).Value = fields("Kode RUP")
    Dim paguVal As String
    paguVal = fields("Pagu Anggaran (Angka)")
    On Error Resume Next
    wsDP.Cells(nextRow, 5).Value = CLng(Replace(Replace(paguVal, ".", ""), ",", ""))
    On Error GoTo 0
    Dim hpsVal As String
    hpsVal = fields("Nilai HPS (Angka)")
    On Error Resume Next
    wsDP.Cells(nextRow, 6).Value = CLng(Replace(Replace(hpsVal, ".", ""), ",", ""))
    On Error GoTo 0
    wsDP.Cells(nextRow, 7).Value = fields("Lokasi Pekerjaan")
    wsDP.Cells(nextRow, 8).Value = fields("Tanggal KAK & HPS")
    wsDP.Cells(nextRow, 9).Value = fields("Nama Penyedia")
    If Not isUpdate Then wsDP.Cells(nextRow, 10).Value = ""

    ' Simpan nomor urut ke Master Data (untuk dipakai generate sebagai prefix folder)
    Dim foundNomor As Boolean
    foundNomor = False
    For r = 3 To wsMD.UsedRange.Rows.Count + 2
        If Trim(CStr(wsMD.Cells(r, 1).Value & "")) = "Nomor Urut Paket" Then
            wsMD.Cells(r, 2).Value = noUrut
            foundNomor = True
            Exit For
        End If
    Next r
    If Not foundNomor Then
        Dim newRow As Long
        newRow = wsMD.UsedRange.Rows.Count + wsMD.UsedRange.Row
        wsMD.Cells(newRow, 1).Value = "Nomor Urut Paket"
        wsMD.Cells(newRow, 2).Value = noUrut
    End If

    ' Auto-generate Nomor Nota Dinas HANYA jika field kosong
    Dim currentND As String
    For r = 3 To wsMD.UsedRange.Rows.Count + 2
        If Trim(CStr(wsMD.Cells(r, 1).Value & "")) = "Nomor Nota Dinas" Then
            currentND = Trim(CStr(wsMD.Cells(r, 2).Value & ""))
            Exit For
        End If
    Next r

    If currentND = "" And SheetExists("Nomor Surat") Then
        Dim wsNS As Worksheet
        Set wsNS = ThisWorkbook.Sheets("Nomor Surat")
        Dim rNS As Long
        For rNS = 2 To 10
            If Trim(CStr(wsNS.Cells(rNS, 1).Value & "")) = "Nota Dinas" Then
                Dim noND As Long
                noND = CLng(wsNS.Cells(rNS, 4).Value) + 1
                wsNS.Cells(rNS, 4).Value = noND
                Dim bulanRomawi As String
                Dim bln As Integer
                bln = Month(Now)
                Dim romawi(12) As String
                romawi(1) = "I" : romawi(2) = "II" : romawi(3) = "III"
                romawi(4) = "IV" : romawi(5) = "V" : romawi(6) = "VI"
                romawi(7) = "VII" : romawi(8) = "VIII" : romawi(9) = "IX"
                romawi(10) = "X" : romawi(11) = "XI" : romawi(12) = "XII"
                bulanRomawi = romawi(bln)
                Dim thn As String
                thn = CStr(Year(Now))
                Dim nomorND As String
                nomorND = "500.2.2.10/" & Format(noND, "000") & "/" & _
                          Format(noUrut, "00") & "/ND/PPK/DISDAG/" & _
                          bulanRomawi & "/" & thn
                Dim rMD2 As Long
                For rMD2 = 3 To wsMD.UsedRange.Rows.Count + 2
                    If Trim(CStr(wsMD.Cells(rMD2, 1).Value & "")) = "Nomor Nota Dinas" Then
                        wsMD.Cells(rMD2, 2).Value = nomorND
                        Exit For
                    End If
                Next rMD2
                Exit For
            End If
        Next rNS
    End If

    ' Patch fields dict sebelum serialize — pastikan nilai aktual (bukan nilai lama dari snapshot)
    fields("Nomor Urut Paket") = CStr(noUrut)

    ' Snapshot tabel lingkup pekerjaan (D12:G12 = header; data ada di E14:E23).
    ' Disimpan sebagai field bernomor agar tetap kompatibel dengan serializer
    ' JSON VBA yang hanya menangani nilai scalar.
    Dim scopeIndex As Long
    For scopeIndex = 1 To 10
        fields("Lingkup Pekerjaan " & CStr(scopeIndex)) = _
            Trim(CStr(wsMD.Cells(13 + scopeIndex, 5).Value & ""))
    Next scopeIndex

    ' Tulis snapshot JSON langsung dari fields ke kolom 11 (VBA murni)
    If Trim(CStr(wsDP.Cells(1, 11).Value & "")) = "" Then
        wsDP.Cells(1, 11).Value = "Snapshot"
        wsDP.Columns(11).ColumnWidth = 30
    End If

    Dim jsonStr As String
    jsonStr = "{"
    Dim k As Variant
    Dim firstEntry As Boolean
    firstEntry = True
    For Each k In fields.Keys
        Dim vStr As String
        vStr = fields(k)
        vStr = Replace(vStr, "\", "\\")
        vStr = Replace(vStr, Chr(34), "\""")
        If Not firstEntry Then jsonStr = jsonStr & ","
        jsonStr = jsonStr & Chr(34) & k & Chr(34) & ":" & Chr(34) & vStr & Chr(34)
        firstEntry = False
    Next k
    jsonStr = jsonStr & "}"
    wsDP.Cells(nextRow, 11).Value = jsonStr

    ThisWorkbook.Save

    Dim msgMode As String
    If isUpdate Then
        msgMode = "diperbarui (update)"
    Else
        msgMode = "ditambahkan (insert baru)"
    End If
    MsgBox "Paket #" & noUrut & " berhasil " & msgMode & " di sheet 'Daftar Paket' dan snapshot disimpan." & Chr(13) & _
           IIf(currentND <> "", "Nomor Nota Dinas dipertahankan: " & currentND, "Nomor Nota Dinas baru di-generate."), _
           vbInformation, "Commit Selesai"
    wsMD.Activate
End Sub

' ─── 6. Nomor Baru (auto-increment dari sheet Nomor Surat) ──────────────────
Sub NomorBaru()
    Dim jenis As String
    jenis = InputBox("Pilih jenis surat:" & Chr(13) & Chr(13) & _
                     "1. Nota Dinas" & Chr(13) & _
                     "2. SPPBJ" & Chr(13) & _
                     "3. SPK" & Chr(13) & _
                     "4. SPMK" & Chr(13) & _
                     "5. Surat Undangan" & Chr(13) & _
                     "6. BA Hasil PL" & Chr(13) & Chr(13) & _
                     "Ketik nama persis (misal: Nota Dinas):", _
                     "Nomor Baru")

    If jenis = "" Then Exit Sub

    ThisWorkbook.Save

    Dim wsh As Object, ret As Long
    Set wsh = CreateObject("WScript.Shell")
    ret = wsh.Run("""" & GetBatPath() & """ --mode nomor-baru --jenis """ & jenis & """", 0, True)
    Set wsh = Nothing

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        MsgBox "✅ Nomor baru berhasil!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 400), vbInformation, "Nomor Baru"
        Application.ScreenUpdating = True
    Else
        MsgBox "❌ Gagal generate nomor baru." & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 400), vbCritical, "Error Nomor Baru"
    End If
End Sub

' ─── 7. Muat dari DB (tarik data Supabase) ──────────────────────────────────
Sub MuatDariDB()
    Dim kode As String
    kode = InputBox("Masukkan Kode RUP paket yang akan dimuat dari database:" & vbNewLine & _
                    "(Contoh: 64312558)", "Muat dari DB")
    If Trim(kode) = "" Then
        MsgBox "Dibatalkan.", vbInformation
        Exit Sub
    End If

    ThisWorkbook.Save

    Dim wsh As Object, ret As Long
    Set wsh = CreateObject("WScript.Shell")
    ret = wsh.Run("""" & GetBatPath() & """ --mode muat-db --kode """ & Trim(kode) & """", 0, True)
    Set wsh = Nothing

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        MsgBox "✅ Muat dari DB berhasil!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 400), vbInformation, "Muat dari DB"
        Application.ScreenUpdating = True
    Else
        MsgBox "❌ Gagal muat dari DB." & Chr(13) & Chr(13) & _
               Left(RingkasLog(logContent), 400), vbCritical, "Error Muat dari DB"
    End If
End Sub

' ─── 8. Generate Pilihan ─────────────────────────────────────────────────────
Sub GeneratePilihan()
    ThisWorkbook.Save

    Dim outputFormat As String
    outputFormat = InputBox("Pilih format output:" & Chr(13) & Chr(13) & _
                            "1 = Word (.docx)" & Chr(13) & _
                            "2 = PDF (.pdf)" & Chr(13) & Chr(13) & _
                            "Default: PDF", "Format Generate Pilihan", "2")

    If Trim(outputFormat) = "" Then
        MsgBox "Dibatalkan.", vbInformation
        Exit Sub
    End If

    Dim formatArg As String
    Select Case Trim(outputFormat)
        Case "1"
            formatArg = "word"
        Case "2"
            formatArg = "pdf"
        Case Else
            MsgBox "Pilihan format tidak valid. Gunakan 1 (Word) atau 2 (PDF).", vbExclamation, "Format tidak valid"
            Exit Sub
    End Select

    ' Ambil daftar template dari filesystem (auto-detect, urut numerik)
    Dim ret As Long
    ret = JalankanBat("--mode list-templates")

    Dim templatesList As String
    templatesList = BacaLog()

    If ret <> 0 Then
        MsgBox "Gagal mendapatkan daftar template:" & Chr(13) & Chr(13) & templatesList, vbCritical, "Error"
        Exit Sub
    End If

    Dim inputIdx As String
    inputIdx = InputBox("Pilih nomor dokumen yang akan di-generate (pisah koma, misal: 1,3,5):" & Chr(13) & Chr(13) & templatesList, "Generate Pilihan")

    If Trim(inputIdx) = "" Then
        MsgBox "Dibatalkan.", vbInformation
        Exit Sub
    End If

    ret = JalankanBat("--mode selective --format " & formatArg & " --files """ & Trim(inputIdx) & """")

    Dim resultLog As String
    resultLog = BacaLog()

    If ret = 0 Then
        MsgBox "✅ Generate pilihan selesai!" & Chr(13) & Chr(13) & _
               Left(RingkasLog(resultLog), 600), vbInformation, "Selesai - " & UCase(formatArg)
    Else
        MsgBox "❌ Generate pilihan gagal." & Chr(13) & Chr(13) & _
               Left(RingkasLog(resultLog), 600), vbCritical, "Error"
    End If

    Application.ScreenUpdating = True
End Sub

' ─── 9. Muat Paket (restore dari snapshot) ───────────────────────────────────
Sub MuatPaket()
    If Not SheetExists("Daftar Paket") Then
        MsgBox "Sheet 'Daftar Paket' tidak ditemukan.", vbCritical
        Exit Sub
    End If

    Dim wsDP As Worksheet
    Set wsDP = ThisWorkbook.Sheets("Daftar Paket")

    Dim lastRow As Long
    lastRow = wsDP.Cells(wsDP.Rows.Count, 2).End(xlUp).Row
    If lastRow < 2 Then
        MsgBox "Tidak ada data paket di sheet 'Daftar Paket'.", vbExclamation
        Exit Sub
    End If

    ' Build daftar untuk InputBox
    Dim daftar As String
    daftar = "Daftar Paket Terdaftar:" & Chr(13) & Chr(13)

    Dim r As Long
    For r = 2 To lastRow
        Dim noVal As String, namaVal As String, kodeVal As String
        noVal   = Trim(CStr(wsDP.Cells(r, 1).Value & ""))
        namaVal = Trim(CStr(wsDP.Cells(r, 2).Value & ""))  ' kolom Nama Singkat
        kodeVal = Trim(CStr(wsDP.Cells(r, 4).Value & ""))

        ' Strip prefix-prefix umum agar nama jadi pendek & unik
        Dim prefiks(5) As String
        prefiks(0) = "Belanja Jasa Konsultansi Perencanaan Rekayasa-Jasa Desain Rekayasa untuk Konstruksi Pondasi serta Struktur Bangunan "
        prefiks(1) = "Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Arsitektur Lainnya "
        prefiks(2) = "Belanja Jasa Konsultansi Perencanaan Arsitektur-Jasa Arsitektur "
        prefiks(3) = "Belanja Jasa Konsultansi Perencanaan Rekayasa-"
        prefiks(4) = "Belanja Jasa Konsultansi Perencanaan "
        prefiks(5) = "Belanja Jasa Konsultansi "
        Dim pi As Integer
        For pi = 0 To 5
            If Left(namaVal, Len(prefiks(pi))) = prefiks(pi) Then
                namaVal = Mid(namaVal, Len(prefiks(pi)) + 1)
                Exit For
            End If
        Next pi

        ' Truncate jika masih panjang
        If Len(namaVal) > 50 Then namaVal = Left(namaVal, 47) & "..."

        If noVal <> "" And kodeVal <> "" Then
            daftar = daftar & noVal & ". " & namaVal & " [" & kodeVal & "]" & Chr(13)
        End If
    Next r

    Dim pilihan As String
    pilihan = InputBox(daftar & Chr(13) & "Masukkan nomor paket yang ingin dimuat (1, 2, dst):", "Muat Paket")
    If Trim(pilihan) = "" Then Exit Sub

    Dim targetNo As Long
    On Error Resume Next
    targetNo = CLng(pilihan)
    On Error GoTo 0

    If targetNo <= 0 Then
        MsgBox "Nomor paket tidak valid.", vbExclamation
        Exit Sub
    End If

    ' Cari baris yang noVal cocok dengan targetNo
    Dim foundRow As Long
    foundRow = 0
    For r = 2 To lastRow
        Dim currNo As Long
        On Error Resume Next
        currNo = CLng(wsDP.Cells(r, 1).Value)
        On Error GoTo 0
        If currNo = targetNo Then
            foundRow = r
            Exit For
        End If
    Next r

    If foundRow = 0 Then
        MsgBox "Nomor paket #" & targetNo & " tidak ditemukan.", vbExclamation
        Exit Sub
    End If

    Dim targetKode As String
    targetKode = Trim(CStr(wsDP.Cells(foundRow, 4).Value & ""))
    If targetKode = "" Then
        MsgBox "Kode RUP kosong pada baris tersebut.", vbExclamation
        Exit Sub
    End If

    If MsgBox("Muat data paket #" & targetNo & "?" & Chr(13) & _
              "Master Data saat ini akan ditimpa dengan data dari snapshot.", _
              vbQuestion + vbYesNo, "Konfirmasi Muat Paket") = vbNo Then Exit Sub

    ThisWorkbook.Save

    Dim wsh As Object, ret As Long
    Set wsh = CreateObject("WScript.Shell")
    ret = wsh.Run("""" & GetBatPath() & """ --mode muat-snapshot --kode """ & targetKode & """", 0, True)
    Set wsh = Nothing

    Dim logContent As String
    logContent = BacaLog()

    If ret = 0 Then
        ' Refresh tampilan — Python sudah tulis ke file/instance, paksa Excel re-read sel
        Application.ScreenUpdating = False
        Dim wsMD As Worksheet
        Set wsMD = ThisWorkbook.Sheets("Master Data")
        wsMD.Activate
        ' Force Excel recalculate & repaint kolom B
        wsMD.Columns(2).Calculate
        Application.ScreenUpdating = True
        MsgBox "Muat snapshot berhasil!" & Chr(13) & Chr(13) & _
               Left(logContent, 500), vbInformation, "Muat Paket Selesai"
    Else
        MsgBox "Muat snapshot gagal (exit " & ret & "):" & Chr(13) & Chr(13) & _
               Left(logContent, 500), vbCritical, "Muat Paket Gagal"
    End If
End Sub

' ─── Helper: cek apakah sheet ada ───────────────────────────────────────────
Private Function SheetExists(sheetName As String) As Boolean
    Dim ws As Object
    On Error Resume Next
    Set ws = ThisWorkbook.Sheets(sheetName)
    SheetExists = Not ws Is Nothing
    On Error GoTo 0
End Function
'''

THISWORKBOOK_CODE = r'''
' PPK_DATE_AUTOCALC_V2
Private Sub Workbook_Open()
    FormatTanggalMaster
    AutoTanggalSelesaiMaster
    AutoUangMukaMaster
    AutoRincianTerminMaster
End Sub

Private Sub FormatTanggalMaster()
    Dim r As Long
    Dim label As String
    With ThisWorkbook.Sheets("Master Data")
        For r = 3 To .UsedRange.Rows.Count + 2
            label = LCase$(Left$(Trim$(CStr(.Cells(r, 1).Value & "")), 7))
            If label = "tanggal" Then .Cells(r, 2).NumberFormat = "@"
        Next r
    End With
End Sub

Private Sub Workbook_SheetChange(ByVal Sh As Object, ByVal Target As Range)
    On Error GoTo Keluar
    If Sh.Name <> "Master Data" Then Exit Sub
    If Target.Cells.CountLarge <> 1 Then Exit Sub
    If Target.Column <> 2 Then Exit Sub

    Dim raw As String
    Dim dt As Date
    Dim dd As Long, mm As Long, yyyy As Long
    Dim label As String
    label = LCase$(Left$(Trim$(CStr(Sh.Cells(Target.Row, 1).Value & "")), 7))

    If label = "tanggal" Then
        raw = Replace(Trim$(CStr(Target.Value2 & "")), " ", "")
        If SemuaDigitMaster(raw) Then
            If Len(raw) = 7 Then raw = "0" & raw
            If Len(raw) = 8 Then
                dd = CLng(Left$(raw, 2))
                mm = CLng(Mid$(raw, 3, 2))
                yyyy = CLng(Right$(raw, 4))
                dt = DateSerial(yyyy, mm, dd)
                If Day(dt) = dd And Month(dt) = mm And Year(dt) = yyyy Then
                    Application.EnableEvents = False
                    Target.NumberFormat = "@"
                    Target.Value = HariTanggalMaster(dt)
                    Application.EnableEvents = True
                End If
            ElseIf IsDate(Target.Value) Then
                Application.EnableEvents = False
                Target.NumberFormat = "@"
                Target.Value = HariTanggalMaster(CDate(Target.Value))
                Application.EnableEvents = True
            End If
        ElseIf IsDate(Target.Value) Then
            Application.EnableEvents = False
            Target.NumberFormat = "@"
            Target.Value = HariTanggalMaster(CDate(Target.Value))
            Application.EnableEvents = True
        End If
    End If

    If Target.Row = BarisMaster("Nilai HPS (Angka)") Or _
       Target.Row = BarisMaster("Nilai Kontrak (Angka)") Or _
       Target.Row = BarisMaster("Tahap Dokumen") Or _
       Target.Row = BarisMaster("Uang Muka (%)") Or _
       Target.Row = BarisMaster("Rincian Termin") Then
        AutoUangMukaMaster
        AutoRincianTerminMaster
    End If

    If Target.Row = BarisMaster("Tahap Dokumen") Or _
       Target.Row = BarisMaster("Tanggal SPK") Or _
       Target.Row = BarisMaster("Tanggal Mulai Kerja") Or _
       Target.Row = BarisMaster("Jangka Waktu (Hari)") Then
        AutoTanggalSelesaiMaster
    End If

Keluar:
    Application.EnableEvents = True
End Sub

Private Function BarisMaster(ByVal wanted As String) As Long
    Dim ws As Worksheet, r As Long, lastRow As Long
    Set ws = ThisWorkbook.Sheets("Master Data")
    lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row
    For r = 1 To lastRow
        If Trim$(CStr(ws.Cells(r, 1).Value & "")) = wanted Then
            BarisMaster = r
            Exit Function
        End If
    Next r
End Function

Private Sub AutoTanggalSelesaiMaster()
    On Error GoTo Keluar
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets("Master Data")

    Dim stageRow As Long, spkRow As Long, startRow As Long
    Dim finishRow As Long, durationRow As Long
    stageRow = BarisMaster("Tahap Dokumen")
    spkRow = BarisMaster("Tanggal SPK")
    startRow = BarisMaster("Tanggal Mulai Kerja")
    finishRow = BarisMaster("Tanggal Selesai Kerja")
    durationRow = BarisMaster("Jangka Waktu (Hari)")
    If stageRow = 0 Or spkRow = 0 Or startRow = 0 Or finishRow = 0 Or durationRow = 0 Then Exit Sub
    If UCase$(Trim$(CStr(ws.Cells(stageRow, 2).Value & ""))) <> "BERKONTRAK" Then Exit Sub

    Dim startText As String, days As Double, startDate As Date
    startText = Trim$(CStr(ws.Cells(startRow, 2).Value & ""))
    If startText = "" Then startText = Trim$(CStr(ws.Cells(spkRow, 2).Value & ""))
    If Not ParseTanggalMaster(startText, startDate) Then Exit Sub
    If Not IsNumeric(ws.Cells(durationRow, 2).Value) Then Exit Sub
    days = CDbl(ws.Cells(durationRow, 2).Value)
    If days <= 0 Then Exit Sub

    Application.EnableEvents = False
    ws.Cells(finishRow, 2).NumberFormat = "@"
    ws.Cells(finishRow, 2).Value = HariTanggalMaster(DateAdd("d", CLng(days) - 1, startDate))

Keluar:
    Application.EnableEvents = True
End Sub

Private Sub AutoUangMukaMaster()
    On Error GoTo Keluar
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets("Master Data")

    Dim stageRow As Long, hpsRow As Long, contractRow As Long, uangRow As Long
    stageRow = BarisMaster("Tahap Dokumen")
    hpsRow = BarisMaster("Nilai HPS (Angka)")
    contractRow = BarisMaster("Nilai Kontrak (Angka)")
    uangRow = BarisMaster("Uang Muka (%)")
    If stageRow = 0 Or hpsRow = 0 Or contractRow = 0 Or uangRow = 0 Then Exit Sub

    Dim stageAddress As String, hpsAddress As String
    Dim contractAddress As String, basisExpression As String, q As String
    stageAddress = ws.Cells(stageRow, 2).Address(False, False)
    hpsAddress = ws.Cells(hpsRow, 2).Address(False, False)
    contractAddress = ws.Cells(contractRow, 2).Address(False, False)
    q = Chr(34)
    basisExpression = "IF(" & stageAddress & "=" & q & "BERKONTRAK" & q & "," & _
        contractAddress & "," & hpsAddress & ")"
    Application.EnableEvents = False
    ws.Cells(uangRow, 2).Formula = "=IFERROR(IF(OR(" & stageAddress & "=" & q & _
        "UPLOAD AWAL" & q & "," & stageAddress & "=" & q & "BERKONTRAK" & q & _
        "),IF(" & basisExpression & "=" & q & q & "," & q & q & ",IF(" & _
        basisExpression & "<50000000," & q & q & ",IF(" & basisExpression & _
        "<=200000000,50,30)))," & q & q & ")," & q & q & ")"

Keluar:
    Application.EnableEvents = True
End Sub

Private Sub AutoRincianTerminMaster()
    On Error GoTo Keluar
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets("Master Data")

    Dim uangRow As Long, rincianRow As Long
    uangRow = BarisMaster("Uang Muka (%)")
    rincianRow = BarisMaster("Rincian Termin")
    If uangRow = 0 Or rincianRow = 0 Then Exit Sub

    Dim uangAddress As String, q As String
    uangAddress = ws.Cells(uangRow, 2).Address(False, False)
    q = Chr(34)
    Application.EnableEvents = False
    ws.Cells(rincianRow, 2).Formula = "=IF(" & uangAddress & "=" & q & q & "," & q & q & "," & _
        q & "1. Uang Muka Sebesar " & q & "&TEXT(" & uangAddress & "," & q & "0" & q & ")&" & _
        q & "% , 2. Termin 1 Progres Kemajuan Fisik " & q & "&UNICHAR(8805)&" & _
        q & " 50%, dan 3. Termin 2 Progres Kemajuan Fisik 100% (PHO)" & q & ")"

Keluar:
    Application.EnableEvents = True
End Sub

Private Function ParseTanggalMaster(ByVal value As String, ByRef result As Date) As Boolean
    Dim raw As String, dd As Long, mm As Long, yyyy As Long
    Dim parts() As String
    raw = Replace(Trim$(value), " ", "")
    If SemuaDigitMaster(raw) Then
        If Len(raw) = 7 Then raw = "0" & raw
        If Len(raw) <> 8 Then Exit Function
        dd = CLng(Left$(raw, 2))
        mm = CLng(Mid$(raw, 3, 2))
        yyyy = CLng(Right$(raw, 4))
        result = DateSerial(yyyy, mm, dd)
        ParseTanggalMaster = (Day(result) = dd And Month(result) = mm And Year(result) = yyyy)
        Exit Function
    End If
    parts = Split(WorksheetFunction.Trim(value), " ")
    If UBound(parts) = 2 And IsNumeric(parts(0)) And IsNumeric(parts(2)) Then
        dd = CLng(parts(0))
        mm = NomorBulanMaster(parts(1))
        yyyy = CLng(parts(2))
        If mm > 0 Then
            result = DateSerial(yyyy, mm, dd)
            ParseTanggalMaster = (Day(result) = dd And Month(result) = mm And Year(result) = yyyy)
            Exit Function
        End If
    End If
    If IsDate(value) Then
        result = CDate(value)
        ParseTanggalMaster = True
    End If
End Function

Private Function NomorBulanMaster(ByVal value As String) As Long
    Select Case LCase$(Trim$(value))
        Case "januari": NomorBulanMaster = 1
        Case "februari", "pebruari": NomorBulanMaster = 2
        Case "maret": NomorBulanMaster = 3
        Case "april": NomorBulanMaster = 4
        Case "mei": NomorBulanMaster = 5
        Case "juni": NomorBulanMaster = 6
        Case "juli": NomorBulanMaster = 7
        Case "agustus": NomorBulanMaster = 8
        Case "september": NomorBulanMaster = 9
        Case "oktober": NomorBulanMaster = 10
        Case "november": NomorBulanMaster = 11
        Case "desember": NomorBulanMaster = 12
    End Select
End Function

Private Function SemuaDigitMaster(ByVal value As String) As Boolean
    Dim i As Long
    If Len(value) = 0 Then Exit Function
    For i = 1 To Len(value)
        If Mid$(value, i, 1) < "0" Or Mid$(value, i, 1) > "9" Then Exit Function
    Next i
    SemuaDigitMaster = True
End Function

Private Function HariTanggalMaster(ByVal dt As Date) As String
    Dim bulan As Variant
    bulan = Array("Januari", "Februari", "Maret", "April", "Mei", "Juni", _
                  "Juli", "Agustus", "September", "Oktober", "November", "Desember")
    HariTanggalMaster = CStr(Day(dt)) & " " & bulan(Month(dt) - 1) & " " & CStr(Year(dt))
End Function
'''


def inject_vba():
    import win32com.client
    import pythoncom

    if not os.path.exists(EXCEL_PATH):
        print(f"ERROR: File tidak ditemukan: {EXCEL_PATH}")
        sys.exit(1)

    print(f"Inject VBA ke: {EXCEL_PATH}")
    print("PASTIKAN Excel sudah ditutup sebelum lanjut...")

    pythoncom.CoInitialize()
    xl = None
    try:
        xl = win32com.client.DispatchEx("Excel.Application")
        xl.Visible = False
        xl.DisplayAlerts = False

        wb = xl.Workbooks.Open(
            os.path.abspath(EXCEL_PATH),
            ReadOnly=False,
            UpdateLinks=False,
        )

        vba_proj = wb.VBProject

        # Hapus modul lama jika ada
        for i in range(vba_proj.VBComponents.Count, 0, -1):
            comp = vba_proj.VBComponents.Item(i)
            if comp.Name == 'ModGeneratePPK':
                vba_proj.VBComponents.Remove(comp)
                print("  Modul lama 'ModGeneratePPK' dihapus.")
                break

        # Inject modul baru
        mod = vba_proj.VBComponents.Add(1)  # vbext_ct_StdModule
        mod.Name = 'ModGeneratePPK'
        mod.CodeModule.AddFromString(VBA_CODE)
        print("  Modul 'ModGeneratePPK' di-inject (9 sub).")

        # Pasang/refresh normalizer tanggal + kalkulasi tanggal selesai.
        this_wb = vba_proj.VBComponents.Item('ThisWorkbook')
        existing_code = ''
        if this_wb.CodeModule.CountOfLines:
            existing_code = this_wb.CodeModule.Lines(1, this_wb.CodeModule.CountOfLines)
        if 'PPK_DATE_AUTOCALC_V2' in existing_code or (
            'Workbook_SheetChange' in existing_code and 'FormatTanggalMaster' in existing_code
        ):
            this_wb.CodeModule.DeleteLines(1, this_wb.CodeModule.CountOfLines)
            this_wb.CodeModule.AddFromString(THISWORKBOOK_CODE)
            print("  Normalizer tanggal Master Data di-refresh.")
        elif 'Workbook_SheetChange' not in existing_code:
            this_wb.CodeModule.AddFromString(THISWORKBOOK_CODE)
            print("  Normalizer tanggal Master Data ditambahkan ke ThisWorkbook.")

        # Setup sheets
        _setup_sheets(xl, wb)
        _ensure_contract_fields(wb)

        # Inject tombol-tombol di sheet Master Data
        _inject_buttons(xl, wb)

        wb.Save()
        wb.Close(SaveChanges=False)
        print("\nVBA berhasil di-inject. Buka Excel dan enable macros.")
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        if xl:
            try:
                xl.Quit()
            except Exception:
                pass
        pythoncom.CoUninitialize()


def _setup_sheets(xl, wb):
    """Buat sheet Daftar Paket, Nomor Surat, Riwayat via COM jika belum ada."""
    import win32com.client

    existing = [wb.Sheets(i+1).Name for i in range(wb.Sheets.Count)]
    tahun = datetime.now().year

    # ── 1. Daftar Paket ───────────────────────────────────────────────────────
    if 'Daftar Paket' not in existing:
        ws_dp = wb.Sheets.Add(After=wb.Sheets(wb.Sheets.Count))
        ws_dp.Name = 'Daftar Paket'
        headers_dp = ['No', 'Nama Paket (Singkat)', 'Nama Paket (Lengkap)',
                      'Kode RUP', 'Pagu (Angka)', 'Nilai HPS (Angka)',
                      'Lokasi Pekerjaan', 'Tanggal KAK & HPS', 'Nama Penyedia',
                      'Status Generate']
        col_widths_dp = [5, 30, 50, 15, 18, 18, 30, 20, 30, 35]
        for col_idx, (hdr, w) in enumerate(zip(headers_dp, col_widths_dp), 1):
            c = ws_dp.Cells(1, col_idx)
            c.Value = hdr
            c.Font.Bold = True
            c.Font.Color = 0xFFFFFF  # putih (BGR)
            c.Interior.Color = 0x794E1F  # biru tua #1F4E79 (BGR)
            ws_dp.Columns(col_idx).ColumnWidth = w
        # Baris contoh
        ws_dp.Cells(2, 1).Value = 1
        ws_dp.Cells(2, 2).Value = '(Isi nama paket singkat)'
        ws_dp.Cells(2, 10).Value = 'Belum di-generate'
        print("  Sheet 'Daftar Paket' dibuat.")
    else:
        print("  Sheet 'Daftar Paket' sudah ada, skip.")

    # ── 2. Nomor Surat ────────────────────────────────────────────────────────
    if 'Nomor Surat' not in existing:
        ws_ns = wb.Sheets.Add(After=wb.Sheets(wb.Sheets.Count))
        ws_ns.Name = 'Nomor Surat'
        headers_ns = ['Jenis', 'Prefix', 'Tahun', 'Nomor Terakhir', 'Contoh (Auto)']
        col_widths_ns = [20, 20, 8, 16, 30]
        for col_idx, (hdr, w) in enumerate(zip(headers_ns, col_widths_ns), 1):
            c = ws_ns.Cells(1, col_idx)
            c.Value = hdr
            c.Font.Bold = True
            c.Font.Color = 0xFFFFFF
            c.Interior.Color = 0x235623  # hijau tua #235623 → BGR #235623
            ws_ns.Columns(col_idx).ColumnWidth = w
        data_ns = [
            ['Nota Dinas',     '600/ND-PPK/',  tahun, 0, f'600/ND-PPK/01/{tahun}'],
            ['SPPBJ',          '600/SPPBJ/',   tahun, 0, f'600/SPPBJ/01/{tahun}'],
            ['SPK',            '600/SPK/',     tahun, 0, f'600/SPK/01/{tahun}'],
            ['SPMK',           '600/SPMK/',    tahun, 0, f'600/SPMK/01/{tahun}'],
            ['Surat Undangan', '600/UND-PL/',  tahun, 0, f'600/UND-PL/01/{tahun}'],
            ['BA Hasil PL',    '600/BA-PL/',   tahun, 0, f'600/BA-PL/01/{tahun}'],
        ]
        for row_idx, row_data in enumerate(data_ns, 2):
            for col_idx, val in enumerate(row_data, 1):
                ws_ns.Cells(row_idx, col_idx).Value = val
        print("  Sheet 'Nomor Surat' dibuat. Edit prefix & tahun sesuai kebutuhan.")
    else:
        print("  Sheet 'Nomor Surat' sudah ada, skip.")

    # ── 3. Riwayat ────────────────────────────────────────────────────────────
    if 'Riwayat' not in existing:
        ws_rw = wb.Sheets.Add(After=wb.Sheets(wb.Sheets.Count))
        ws_rw.Name = 'Riwayat'
        headers_rw = ['No', 'Nama Paket (Singkat)', 'Kode RUP',
                       'Pagu Anggaran', 'Tanggal Generate', 'Folder Output', 'Status']
        col_widths_rw = [5, 35, 15, 18, 20, 40, 30]
        for col_idx, (hdr, w) in enumerate(zip(headers_rw, col_widths_rw), 1):
            c = ws_rw.Cells(1, col_idx)
            c.Value = hdr
            c.Font.Bold = True
            c.Font.Color = 0xFFFFFF
            c.Interior.Color = 0x8B2D7B  # ungu #7B2D8B → BGR 0x8B2D7B
            ws_rw.Columns(col_idx).ColumnWidth = w
        print("  Sheet 'Riwayat' dibuat.")
    else:
        print("  Sheet 'Riwayat' sudah ada, skip.")


def _ensure_contract_fields(wb):
    """Tambahkan field tahap/substansi tanpa mengubah styling existing."""
    ws = wb.Sheets('Master Data')
    fields = {
        31: ('Tahap Dokumen', 'UPLOAD AWAL'),
        70: ('Nilai Kontrak (Angka)', ''),
        71: ('Nilai Kontrak (Terbilang)', ''),
        87: ('Uang Muka (%)', ''),
        88: ('Sistem Pembayaran', ''),
        89: ('Rincian Termin', ''),
        90: ('Masa Pemeliharaan (Hari)', ''),
        91: ('Retensi (%)', ''),
        101: ('NIP Wakil Sah', ''),
    }
    for row, (label, default) in fields.items():
        if str(ws.Cells(row, 1).Value or '').strip() == '':
            if row == 101:
                # Baris 101 sudah disediakan template sebagai ruang kosong.
                # Salin format baris field penyedia terakhir tanpa insert row,
                # agar layout/VBA lama tetap stabil.
                try:
                    ws.Range('A100:B100').Copy(Destination=ws.Range('A101:B101'))
                    ws.Cells(row, 2).ClearContents()
                except Exception as exc:
                    print(f"  [WARN] Format NIP Wakil Sah gagal disalin: {exc}")
            ws.Cells(row, 1).Value = label
        if label == 'Tahap Dokumen' and str(ws.Cells(row, 2).Value or '').strip() == '':
            ws.Cells(row, 2).Value = default

    stage_cell = ws.Cells(31, 2)
    try:
        stage_cell.Validation.Delete()
    except Exception:
        pass
    try:
        stage_cell.Validation.Add(
            Type=3, AlertStyle=1, Operator=1,
            # Excel Indonesia memakai titik koma sebagai list separator.
            Formula1='UPLOAD AWAL;BERKONTRAK',
        )
        stage_cell.Validation.IgnoreBlank = True
        stage_cell.Validation.InCellDropdown = True
    except Exception as exc:
        print(f"  [WARN] Validasi Tahap Dokumen gagal: {exc}")
    try:
        # Upload Awal memakai HPS sebagai indikasi; Berkontrak memakai Nilai
        # Kontrak final. Nilai Kontrak sudah ada di field B70 pada template.
        ws.Range('B88').Formula = '=IFERROR(IF(OR(B31="UPLOAD AWAL",B31="BERKONTRAK"),IF(IF(B31="BERKONTRAK",B70,B13)="","",IF(IF(B31="BERKONTRAK",B70,B13)<50000000,"",IF(IF(B31="BERKONTRAK",B70,B13)<=200000000,50,30))),""),"")'
        ws.Range('B90').Formula = '=IF(B88="","","1. Uang Muka Sebesar "&TEXT(B88,"0")&"% , 2. Termin 1 Progres Kemajuan Fisik "&UNICHAR(8805)&" 50%, dan 3. Termin 2 Progres Kemajuan Fisik 100% (PHO)")'
        print("  Formula uang muka otomatis dipasang di Master Data!B88.")
        print("  Formula rincian termin otomatis dipasang di Master Data!B90.")
    except Exception as exc:
        print(f"  [WARN] Formula uang muka otomatis gagal dipasang: {exc}")
    print("  Field Tahap Dokumen/kontrak dipastikan tanpa mengubah styling.")


def _inject_buttons(xl, wb):
    """Tambahkan tombol yang benar-benar belum ada tanpa menyentuh layout."""
    try:
        ws = wb.Sheets('Master Data')
        desired = [
            ('Generate Dokumen', 'ModGeneratePPK.GenerateDokumen', 2, 0),
            ('Generate Pilihan', 'ModGeneratePPK.GeneratePilihan', 2, 1),
            ('Print PDF', 'ModGeneratePPK.PrintPDF', 3, 0),
            ('Print Pilihan PDF', 'ModGeneratePPK.PrintPilihanPDF', 3, 1),
            ('Print All PDF', 'ModGeneratePPK.PrintAllPDF', 4, 0),
            ('Generate Semua', 'ModGeneratePPK.GenerateSemua', 4, 1),
            ('Commit Paket', 'ModGeneratePPK.CommitPaket', 5, 0),
            ('Nomor Baru', 'ModGeneratePPK.NomorBaru', 5, 1),
            ('Muat dari DB', 'ModGeneratePPK.MuatDariDB', 6, 0),
            ('Muat Paket', 'ModGeneratePPK.MuatPaket', 6, 1),
        ]
        existing_macros = set()
        for i in range(1, ws.Shapes.Count + 1):
            try:
                action = str(ws.Shapes(i).OnAction or '').strip()
                if action:
                    existing_macros.add(action)
            except Exception:
                pass

        # Posisi hanya dipakai untuk tombol baru; tombol existing tidak digeser.
        lefts = [ws.Range('D2').Left + 2, ws.Range('F2').Left + 2]
        widths = [ws.Range('D2:E2').Width - 4, ws.Range('F2:G2').Width - 4]
        top = ws.Range('D2').Top
        added = 0
        for caption, macro, row, col in desired:
            if macro in existing_macros:
                continue
            btn = ws.Buttons().Add(lefts[col], top + (row - 2) * 30, widths[col], 25)
            btn.Caption = caption
            btn.OnAction = macro
            added += 1
        print(f"  Tombol Master Data dipertahankan; {added} tombol baru ditambahkan.")
    except Exception as e:
        print(f"  [WARN] Inject tombol gagal: {e} — tambahkan tombol manual jika perlu.")


if __name__ == '__main__':
    inject_vba()
